server:
  port: 8080

management:
  endpoint:
    health:
      probes:
        enabled: true

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?user=${DB_USER}&password=${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

jwt-token:
  salt: ${JWT_TOKEN_SALT:}
  expiration: ${JWT_TOKEN_EXPIRATION:}
