server:
  port: 8085

management:
  endpoint:
    health:
      probes:
        enabled: true

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_NAME}?user=${POSTGRES_USER}&password=${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  autoconfigure:
    exclude: net.devh.boot.grpc.server.autoconfigure.GrpcServerMetricAutoConfiguration

jwt-token:
  salt: ${JWT_TOKEN_SALT:}
  expiration: ${JWT_TOKEN_EXPIRATION:}
