# bank-account-codegen-config.yaml for bank-account api + server

output: internal/handler/http/bank-account-api/bank_account_gen.go
package: bank
generate:
  - types
  - gin-server

# To RUN from root:
# oapi-codegen --config .codegen/bank-account-codegen-config.yaml .codegen/bank-account-codegen.yaml
