# bank-account-codegen-config.yaml for bank-account api + server

output: internal/handler/generated/bank-account/bank-account.go
package: bank_account
generate:
  - types
  - gin-server

# To RUN from root:
# oapi-codegen --config .codegen/bank-account-codegen-config.yaml .codegen/bank-account-codegen.yaml
