openapi: 3.0.0
info:
  title: Discount Service API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /discounts/{id}:
    get:
      summary: Get discount by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiscountGet'
  /discounts:
    get:
      summary: List discounts
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DiscountGet'
    post:
      summary: Create a discount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DiscountCreate'
      responses:
        '200':
          description: Successful operation
    put:
      summary: Update a discount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DiscountUpdate'
      responses:
        '200':
          description: Successful operation
  /discounts/{id}/end:
    put:
      summary: End a discount
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
components:
  schemas:
    DiscountGet:
      type: object
      properties:
        UUID:
          type: string
          format: uuid
        CreatedBy:
          type: string
          format: uuid
        Percent:
          type: number
        StandAlone:
          type: boolean
        StartedAt:
          type: string
          format: date-time
        EndedAt:
          type: string
          format: date-time
        Status:
          type: string
        CreatedAt:
          type: string
          format: date-time
        LastUpdateAt:
          type: string
          format: date-time
    DiscountCreate:
      type: object
      properties:
        CreatedBy:
          type: string
          format: uuid
        Percent:
          type: number
        StandAlone:
          type: boolean
        StartedAt:
          type: string
          format: date-time
        EndedAt:
          type: string
          format: date-time
        Status:
          type: string
      required:
        - CreatedBy
        - Percent
        - StandAlone
        - StartedAt
        - EndedAt
        - Status
    DiscountUpdate:
      type: object
      required:
        - UUID
        - CreatedBy
        - Percent
        - StandAlone
        - StartedAt
        - EndedAt
        - Status
      properties:
        UUID:
          type: string
          format: uuid
        CreatedBy:
          type: string
          format: uuid
        Percent:
          type: number
        StandAlone:
          type: boolean
        StartedAt:
          type: string
          format: date-time
        EndedAt:
          type: string
          format: date-time
        Status:
          type: string
    DiscountFilter:
      type: object
      properties:
        UUID:
          type: string
          format: uuid
        CreatedBy:
          type: string
          format: uuid
        Percent:
          type: number
        StandAlone:
          type: boolean
        Status:
          type: string
