# discount-codegen-config.yaml for discount api + server

output: internal/handler/generated/discount/discount.go
package: discount
generate:
  - types
  - gin-server

# To RUN from root:
# oapi-codegen --config .codegen/discount-codegen-config.yaml .codegen/discount-codegen.yaml
