# finance-codegen-config.yaml for finance api + server

output: internal/handler/http/generated-api/generated_gen.go
package: finance
generate:
  - types
  - gin-server

# To RUN from root:
# oapi-codegen --config .codegen/finance-codegen-config.yaml .codegen/finance-codegen.yaml
