# payment-codegen-config.yaml for payment api + server

output: internal/handler/generated/payment/payment.go
package: payment
generate:
  - types
  - gin-server

# To RUN from root:
# oapi-codegen --config .codegen/payment-codegen-config.yaml .codegen/payment-codegen.yaml
