openapi: 3.0.0
info:
  title: Payment Service API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1/finances
paths:
  /payments/{uuid}:
    get:
      operationId: get
      summary: Get payment by UUID
      parameters:
        - in: path
          name: uuid
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentGet'
        '400':
          description: Incorrect payment UUID
        '404':
          description: Payment not found by UUID
  /payments:
    get:
      operationId: getList
      summary: List payments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentFilter'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaymentGet'
    post:
      operationId: create
      summary: Create a payment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentCreate'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Incorrect payment data
components:
  schemas:
    PaymentData:
      type: object
      properties: { }
    PaymentGet:
      type: object
      properties:
        UUID:
          type: string
          format: uuid
        Sender:
          type: string
          format: uuid
        Receiver:
          type: string
          format: uuid
        Data:
          $ref: '#/components/schemas/PaymentData'
        URL:
          type: string
        Status:
          type: string
        EndedAt:
          type: string
          format: date-time
        CreatedAt:
          type: string
          format: date-time
      required:
        - UUID
        - Sender
        - Receiver
        - Data
        - URL
        - Status
        - EndedAt
        - CreatedAt
    PaymentCreate:
      type: object
      properties:
        Sender:
          type: string
          format: uuid
        Receiver:
          type: string
          format: uuid
        Data:
          $ref: '#/components/schemas/PaymentData'
        URL:
          type: string
        Status:
          type: string
        EndedAt:
          type: string
          format: date-time
      required:
        - Sender
        - Receiver
        - Data
        - URL
        - Status
        - EndedAt
    PaymentFilter:
      type: object
      properties:
        UUID:
          type: string
          format: uuid
        Sender:
          type: string
          format: uuid
        Receiver:
          type: string
          format: uuid
        URL:
          type: string
        Status:
          type: string
        EndedAt:
          type: string
          format: date-time
