# payout-request-codegen-config.yaml for payout-request api + server

output: internal/handler/http/payout/payout.go
package: payout
generate:
  - types
  - gin-server

# To RUN from root:
# oapi-codegen --config .codegen/payout-request-codegen-config.yaml .codegen/payout-request-codegen.yaml
