# payout-request-codegen-config.yaml for payout-request api + server

output: xor-go/services/finances/internal/handler/generated/payout-request/payout-request.go
package: payout-request
generate:
  - types
  - gin-server


# To RUN from root:
# oapi-codegen --config xor-go/services/finances/.codegen/payout-request-codegen-config.yaml xor-go/services/finances/.codegen/payout-request-codegen.yaml
