openapi: 3.0.0
info:
  title: Payout Request Service API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /payout-requests/{id}:
    get:
      operationId: get
      summary: Get payout request by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PayoutRequestGet'
  /payout-requests:
    get:
      operationId: getList
      summary: List payout requests
      parameters:
        - in: query
          name: filter
          schema:
            $ref: '#/components/schemas/PayoutRequestFilter'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PayoutRequestGet'
    post:
      operationId: create
      summary: Create a payout request
      parameters:
        - in: query
          name: model
          required: true
          schema:
            $ref: '#/components/schemas/PayoutRequestCreate'
      responses:
        '200':
          description: Successful operation
  /payout-requests/{id}/archive:
    put:
      operationId: archive
      summary: Archive a payout request
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
components:
  schemas:
    PayoutRequestData:
      type: object
      properties: { }
    PayoutRequestGet:
      type: object
      properties:
        UUID:
          type: string
          format: uuid
        Receiver:
          type: string
          format: uuid
        Amount:
          type: number
        Data:
          $ref: '#/components/schemas/PayoutRequestData'
        ReceivedAt:
          type: string
          format: date-time
      required:
        - UUID
        - Receiver
        - Amount
        - Data
        - ReceivedAt
    PayoutRequestCreate:
      type: object
      properties:
        Receiver:
          type: string
          format: uuid
        Amount:
          type: number
        Data:
          $ref: '#/components/schemas/PayoutRequestData'
        ReceivedAt:
          type: string
          format: date-time
      required:
        - Receiver
        - Amount
        - Data
        - ReceivedAt
    PayoutRequestFilter:
      type: object
      properties:
        UUID:
          type: string
          format: uuid
        Receiver:
          type: string
          format: uuid
        Amount:
          type: number
        ReceivedAt:
          type: string
          format: date-time
