openapi: 3.0.0
info:
  title: Product Service API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1/finances
paths:
  /products/{id}:
    get:
      tags:
        - Product
      summary: Get product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductGet'
  /products:
    get:
      tags:
        - Product
      summary: List products
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductFilter'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductGet'
    post:
      tags:
        - Product
      summary: Create a product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreate'
      responses:
        '200':
          description: Successful operation
    put:
      tags:
        - Product
      summary: Update a product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductUpdate'
      responses:
        '200':
          description: Successful operation
  /products/list:
    post:
      tags:
        - Product
      summary: Create many products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ProductCreate'
      responses:
        '200':
          description: Successful operation
  /products/{id}/disable:
    put:
      tags:
        - Product
      summary: Disable a product
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
  /products/price/{uuids}:
    get:
      tags:
        - Product
      summary: Get products price with discounts
      parameters:
        - in: path
          name: uuids
          required: true
          schema:
            type: array
            items:
              type: string
              format: uuid
      responses:
        '200':
          description: Successful operation
components:
  schemas:
    ProductGet:
      type: object
      properties:
        UUID:
          type: string
          format: uuid
        Name:
          type: string
        Info:
          type: string
        Price:
          type: number
        IsAvailable:
          type: boolean
        CreatedAt:
          type: string
          format: date-time
        LastUpdatedAt:
          type: string
          format: date-time
      required:
        - UUID
        - Name
        - Info
        - Price
        - IsAvailable
        - CreatedAt
        - LastUpdatedAt
    ProductCreate:
      type: object
      properties:
        Name:
          type: string
        Info:
          type: string
        Price:
          type: number
        IsAvailable:
          type: boolean
      required:
        - Name
        - Info
        - Price
        - IsAvailable
    ProductUpdate:
      type: object
      properties:
        UUID:
          type: string
          format: uuid
        Name:
          type: string
        Info:
          type: string
        Price:
          type: number
        IsAvailable:
          type: boolean
      required:
        - UUID
        - Name
        - Info
        - Price
        - IsAvailable
    ProductFilter:
      type: object
      properties:
        UUID:
          type: string
          format: uuid
        Name:
          type: string
        Price:
          type: number
        IsAvailable:
          type: boolean
