openapi: 3.0.0
info:
  title: Purchase Request Service API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1/finances
paths:
  /purchase-requests/{id}:
    get:
      tags:
        - Purchase request
      summary: Get purchase request by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseRequestGet'
  /purchase-requests:
    get:
      tags:
        - Purchase request
      summary: List purchase requests
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseRequestFilter'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PurchaseRequestGet'
    post:
      tags:
        - Purchase request
      summary: Create a purchase request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseRequestCreate'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelUUID'
  /purchase-requests/{id}/archive:
    put:
      tags:
        - Purchase request
      summary: Archive a purchase request
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
components:
  schemas:
    PurchaseRequestGet:
      type: object
      required:
        - UUID
        - Products
        - WebhookURL
        - CreatedAt
        - Status
      properties:
        UUID:
          type: string
          format: uuid
        Sender:
          type: string
          format: uuid
        Receiver:
          type: string
          format: uuid
        Products:
          type: array
          items:
            type: string
            format: uuid
        WebhookURL:
          type: string
        Status:
          type: string
        CreatedAt:
          type: string
          format: date-time
    PurchaseRequestCreate:
      type: object
      required:
        - Products
        - WebhookURL
        - CreatedAt
        - Status
      properties:
        Sender:
          type: string
          format: uuid
        Receiver:
          type: string
          format: uuid
        Status:
          type: string
        Products:
          type: array
          items:
            type: string
            format: uuid
        WebhookURL:
          type: string
        CreatedAt:
          type: string
          format: date-time
    PurchaseRequestFilter:
      type: object
      properties:
        UUID:
          type: string
          format: uuid
        Sender:
          type: string
          format: uuid
        Receiver:
          type: string
          format: uuid
        Status:
          type: string
        WebhookURL:
          type: string
        CreatedAt:
          type: string
          format: date-time
    ModelUUID:
      type: object
      properties:
        UUID:
          type: string
          format: uuid
      required:
        - UUID
