http:
  host: "localhost"
  port: 6790

telegram-bot:
  token: "7136740171:AAF4HGdyF_2wGyCZ7dtxSMzGRVB2TQQDGFQ"

postgres:
  host: "localhost"
  port: "5432"
  dbname: "postgres"
  user: "postgres"
  password: "qwerty"
