version: '3.9'

services:
  courses-svc:
    build:
      context: '.'
      dockerfile: './xor-go/courses.Dockerfile'
    image: 'courses-svc:latest'
    ports:
      - "8080:8080"
    depends_on:
      mongo1:
        condition: service_healthy
      mongo2:
        condition: service_started
      mongo3:
        condition: service_started
    environment:
      - DB_PASSWORD=password

  #  MONGO

  mongo1:
    image: mongo:7.0
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "27017" ]
    ports:
      - "27017:27017"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo1:27017',priority:1},{_id:1,host:'mongo2:27018',priority:0.5},{_id:2,host:'mongo3:27019',priority:0.5}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"

  mongo2:
    container_name: mongo2
    image: mongo:7.0
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "27018" ]
    ports:
      - "27018:27018"
    volumes:
      - "mongo2_data:/data/db"
      - "mongo2_config:/data/configdb"

  mongo3:
    container_name: mongo3
    image: mongo:7.0
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "27019" ]
    ports:
      - "27019:27019"
    volumes:
      - "mongo3_data:/data/db"
      - "mongo3_config:/data/configdb"

  # POSTGRESQL

  postgresql_db:
    restart: always
    image: postgres:latest
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d finances_db" ]
      interval: 5s
      timeout: 10s
      retries: 5

  # FINANCES

  finances-svc:
    image: 'finances-svc:latest'
    build:
      context: '.'
      dockerfile: './xor-go/finances.Dockerfile'
    ports:
      - "8082:8082"
    depends_on:
      postgresql_db:
        condition: service_healthy

  # PAYMENTS

  payments-svc:
    image: 'payments-svc:latest'
    build:
      context: './xor-python/services/payments'
      dockerfile: './deploy/Dockerfile'
    ports:
      - "8083:8083"

  # SAGE

  sage-svc:
    image: 'sage-svc:latest'
    build:
      context: '.'
      dockerfile: './xor-go/sage.Dockerfile'
    ports:
      - "8084:8084"

  # IDM

  idm-svc:
    image: 'idm-svc:latest'
    build:
      context: '.'
      dockerfile: './xor-java/idm/Dockerfile'
    ports:
      - "8085:8085"
    depends_on:
      postgresql_db:
        condition: service_healthy

  # FEEDBACK

  feedback-svc:
    image: 'feedback-svc:latest'
    build:
      context: '.'
      dockerfile: './xor-java/feedback/Dockerfile'
    ports:
      - "8086:8086"
    depends_on:
      postgresql_db:
        condition: service_healthy

  # NOTIFICATION

  notifications-svc:
    image: 'notifications-svc:latest'
    build:
      context: '.'
      dockerfile: './xor-java/notifications/Dockerfile'
    ports:
      - "8087:8087"
    depends_on:
      postgresql_db:
        condition: service_healthy
    environment:
      MAIL_USERNAME: admin
      MAIL_PASSWORD: password
      EMAIL_NOTIFICATIONS_SENDER_EMAIL: string

networks:
  courses:
    name: courses

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongo1_config:
  mongo2_config:
  mongo3_config:

