// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package idmproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IdmClient is the client API for Idm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdmClient interface {
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
}

type idmClient struct {
	cc grpc.ClientConnInterface
}

func NewIdmClient(cc grpc.ClientConnInterface) IdmClient {
	return &idmClient{cc}
}

func (c *idmClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, "/idmproto.Idm/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdmServer is the server API for Idm service.
// All implementations must embed UnimplementedIdmServer
// for forward compatibility
type IdmServer interface {
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
	mustEmbedUnimplementedIdmServer()
}

// UnimplementedIdmServer must be embedded to have forward compatible implementations.
type UnimplementedIdmServer struct {
}

func (UnimplementedIdmServer) Verify(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedIdmServer) mustEmbedUnimplementedIdmServer() {}

// UnsafeIdmServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdmServer will
// result in compilation errors.
type UnsafeIdmServer interface {
	mustEmbedUnimplementedIdmServer()
}

func RegisterIdmServer(s grpc.ServiceRegistrar, srv IdmServer) {
	s.RegisterService(&Idm_ServiceDesc, srv)
}

func _Idm_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdmServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idmproto.Idm/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdmServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Idm_ServiceDesc is the grpc.ServiceDesc for Idm service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Idm_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "idmproto.Idm",
	HandlerType: (*IdmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Verify",
			Handler:    _Idm_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xor-go/proto/idm/idm.proto",
}
