server:
  port: 8087

management:
  endpoint:
    health:
      probes:
        enabled: true

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_NAME}?user=${POSTGRES_USER}&password=${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.yandex.ru
    port: 25
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: false

email-notification:
  sender-email: ${EMAIL_NOTIFICATIONS_SENDER_EMAIL}
