server:
  port: 8080

management:
  endpoint:
    health:
      probes:
        enabled: true

spring:
  data:
    mongodb:
      uri: ${URI}
      database: ${DB}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?user=${DB_USER}&password=${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.yandex.ru
    port: 25
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: false

email-notification:
  from: ${EMAIL_NOTIFICATIONS_FROM}
