server:
  port: 8087

management:
  endpoint:
    health:
      probes:
        enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?user=postgres&password=qwerty
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.yandex.ru
    port: 25
    username: email
    password: password
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: false

email-notification:
  sender-email: email
