apiVersion: "1.0.0"

app:
  name: "template"
  env: "local"

logger:
  env: "dev" # "prod"
  level: "info"
  outputs:
    - "stdout"
  error_outputs:
    - "stderr"
  encoding: "json"
  sentry_dsn: ""
  sentry_level: "error"

metrics:
  enable: false
  dsn: "<sentry_dsn_for_service>"

graceful_shutdown:
  delay: "5s"
  wait_timeout: "5s"
  callback_timeout: "2s"

http:
  host: "localhost"
  port: 8080
  read_timeout: "1s"
  write_timeout: "1s"

location_client:
  uri: "http://localhost:8084"

mongo:
  database: template
  uri: "mongodb://localhost:27017,localhost:27018,localhost:27019/template?replicaSet=rs0&authSource=admin&readPreference=primaryPreferred"

migrations_mongo:
  uri: "mongodb://localhost:27017,localhost:27018,localhost:27019/template?replicaSet=rs0&authSource=admin&readPreference=primaryPreferred"
  path: "./projects/template/migrations"
  enabled: true

kafka_reader:
  brokers:
    - "TODO_broker"
  topic: "TODO_topic_here"
  id_group: "TODO_id_group_here"
  min_bytes: 1
  max_bytes: 2048

scraper:
  scrape_interval: "5s"

long_poll:
  long_poll_timeout: "10s"

tracer:
  enable: false
  exp_target: "jaeger-all-in-one:4317"
