app:
  name: "sage"
  env: "dev"
  version: "0.0"

http:
  host: "localhost"
  port: 8080
  read_timeout: "1s"
  write_timeout: "1s"

logger:
  env: "dev" # "prod"
  level: "debug"
  outputs:
    - "stdout"
  error_outputs:
    - "stderr"
  encoding: "json"
  sentry_level: "error"
  sentry_dsn: ""

idm-client:
  host: "localhost:6134"
