logger:
  environment: "dev"
  level: "debug"
  encoding: "json"
  output_paths:
    - "stdout"
    - "path/to/logging.log"
  error_output_paths:
    - "stderr"
    - "path/to/logging.log"

http:
  host: "localhost"
  port: "8080"
  read_timeout: "1s"
  write_timeout: "1s"