system:
  service: "sage"
  environment: "dev"
  dc: "local"

logger:
  environment: "dev"
  level: "debug"
  encoding: "json"
  output_paths:
    - "stdout"
    - "path/to/logging.log"
  error_output_paths:
    - "stderr"
    - "path/to/logging.log"

http:
  host: "host"
  port: "port"
  read_timeout: "6s"
  write_timeout: "6s"

mongo:
  uri: "mongodb://host:port"
  database: "sage"
  timeout: "3s"
