openapi: 3.0.0
info:
  title: Courses API
  version: 1.0.0
paths:
  /teachers:
    get:
      summary: Get all teachers
      responses:
        '200':
          description: A list of teachers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Teacher'
    post:
      summary: Create a new teacher
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Teacher'
      responses:
        '201':
          description: Teacher created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Teacher'
  /teachers/{teacherID}:
    parameters:
      - name: teacherID
        in: path
        required: true
        description: ID of the teacher
        schema:
          type: string
          format: uuid
    get:
      summary: Get a teacher by ID
      responses:
        '200':
          description: Retrieved teacher
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Teacher'
    put:
      summary: Update a teacher
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Teacher'
      responses:
        '200':
          description: Teacher updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Teacher'
    delete:
      summary: Delete a teacher
      responses:
        '204':
          description: Teacher deleted successfully

components:
  schemas:
    Teacher:
      type: object
      properties:
        ID:
          type: string
          format: uuid
        AccountID:
          type: string
          format: uuid
        BankAccountUUID:
          type: string
          format: uuid
      required:
        - ID
        - AccountID
        - BankAccountUUID