// Package product provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package product

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ProductCreate defines model for ProductCreate.
type ProductCreate struct {
	Info        string  `json:"Info"`
	IsAvailable bool    `json:"IsAvailable"`
	Name        string  `json:"Name"`
	Price       float32 `json:"Price"`
}

// ProductFilter defines model for ProductFilter.
type ProductFilter struct {
	IsAvailable *bool               `json:"IsAvailable,omitempty"`
	Name        *string             `json:"Name,omitempty"`
	Price       *float32            `json:"Price,omitempty"`
	UUID        *openapi_types.UUID `json:"UUID,omitempty"`
}

// ProductGet defines model for ProductGet.
type ProductGet struct {
	CreatedAt     time.Time          `json:"CreatedAt"`
	Info          string             `json:"Info"`
	IsAvailable   bool               `json:"IsAvailable"`
	LastUpdatedAt time.Time          `json:"LastUpdatedAt"`
	Name          string             `json:"Name"`
	Price         float32            `json:"Price"`
	UUID          openapi_types.UUID `json:"UUID"`
}

// ProductUpdate defines model for ProductUpdate.
type ProductUpdate struct {
	Info        string             `json:"Info"`
	IsAvailable bool               `json:"IsAvailable"`
	Name        string             `json:"Name"`
	Price       float32            `json:"Price"`
	UUID        openapi_types.UUID `json:"UUID"`
}

// PostProductsListJSONBody defines parameters for PostProductsList.
type PostProductsListJSONBody = []ProductCreate

// GetProductsJSONRequestBody defines body for GetProducts for application/json ContentType.
type GetProductsJSONRequestBody = ProductFilter

// PostProductsJSONRequestBody defines body for PostProducts for application/json ContentType.
type PostProductsJSONRequestBody = ProductCreate

// PutProductsJSONRequestBody defines body for PutProducts for application/json ContentType.
type PutProductsJSONRequestBody = ProductUpdate

// PostProductsListJSONRequestBody defines body for PostProductsList for application/json ContentType.
type PostProductsListJSONRequestBody = PostProductsListJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List products
	// (GET /products)
	GetProducts(c *gin.Context)
	// Create a product
	// (POST /products)
	PostProducts(c *gin.Context)
	// Update a product
	// (PUT /products)
	PutProducts(c *gin.Context)
	// Create many products
	// (POST /products/list)
	PostProductsList(c *gin.Context)
	// Get products price with discounts
	// (GET /products/price/{uuids})
	GetProductsPriceUuids(c *gin.Context, uuids []openapi_types.UUID)
	// Get product by ID
	// (GET /products/{id})
	GetProductsId(c *gin.Context, id openapi_types.UUID)
	// Disable a product
	// (PUT /products/{id}/disable)
	PutProductsIdDisable(c *gin.Context, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetProducts operation middleware
func (siw *ServerInterfaceWrapper) GetProducts(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProducts(c)
}

// PostProducts operation middleware
func (siw *ServerInterfaceWrapper) PostProducts(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostProducts(c)
}

// PutProducts operation middleware
func (siw *ServerInterfaceWrapper) PutProducts(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutProducts(c)
}

// PostProductsList operation middleware
func (siw *ServerInterfaceWrapper) PostProductsList(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostProductsList(c)
}

// GetProductsPriceUuids operation middleware
func (siw *ServerInterfaceWrapper) GetProductsPriceUuids(c *gin.Context) {

	var err error

	// ------------- Path parameter "uuids" -------------
	var uuids []openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "uuids", c.Param("uuids"), &uuids)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter uuids: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProductsPriceUuids(c, uuids)
}

// GetProductsId operation middleware
func (siw *ServerInterfaceWrapper) GetProductsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProductsId(c, id)
}

// PutProductsIdDisable operation middleware
func (siw *ServerInterfaceWrapper) PutProductsIdDisable(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutProductsIdDisable(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/products", wrapper.GetProducts)
	router.POST(options.BaseURL+"/products", wrapper.PostProducts)
	router.PUT(options.BaseURL+"/products", wrapper.PutProducts)
	router.POST(options.BaseURL+"/products/list", wrapper.PostProductsList)
	router.GET(options.BaseURL+"/products/price/:uuids", wrapper.GetProductsPriceUuids)
	router.GET(options.BaseURL+"/products/:id", wrapper.GetProductsId)
	router.PUT(options.BaseURL+"/products/:id/disable", wrapper.PutProductsIdDisable)
}
