// Package product provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package product

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ProductCreate defines model for ProductCreate.
type ProductCreate struct {
	Info        string  `json:"Info"`
	IsAvailable bool    `json:"IsAvailable"`
	Name        string  `json:"Name"`
	Price       float32 `json:"Price"`
}

// ProductFilter defines model for ProductFilter.
type ProductFilter struct {
	IsAvailable *bool               `json:"IsAvailable,omitempty"`
	Name        *string             `json:"Name,omitempty"`
	Price       *float32            `json:"Price,omitempty"`
	UUID        *openapi_types.UUID `json:"UUID,omitempty"`
}

// ProductGet defines model for ProductGet.
type ProductGet struct {
	CreatedAt     time.Time          `json:"CreatedAt"`
	Info          string             `json:"Info"`
	IsAvailable   bool               `json:"IsAvailable"`
	LastUpdatedAt time.Time          `json:"LastUpdatedAt"`
	Name          string             `json:"Name"`
	Price         float32            `json:"Price"`
	UUID          openapi_types.UUID `json:"UUID"`
}

// ProductUpdate defines model for ProductUpdate.
type ProductUpdate struct {
	Info        string             `json:"Info"`
	IsAvailable bool               `json:"IsAvailable"`
	Name        string             `json:"Name"`
	Price       float32            `json:"Price"`
	UUID        openapi_types.UUID `json:"UUID"`
}

// CreateManyJSONBody defines parameters for CreateMany.
type CreateManyJSONBody = []ProductCreate

// GetListJSONRequestBody defines body for GetList for application/json ContentType.
type GetListJSONRequestBody = ProductFilter

// CreateJSONRequestBody defines body for Create for application/json ContentType.
type CreateJSONRequestBody = ProductCreate

// UpdateJSONRequestBody defines body for Update for application/json ContentType.
type UpdateJSONRequestBody = ProductUpdate

// CreateManyJSONRequestBody defines body for CreateMany for application/json ContentType.
type CreateManyJSONRequestBody = CreateManyJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List products
	// (GET /products)
	GetList(c *gin.Context)
	// Create a product
	// (POST /products)
	Create(c *gin.Context)
	// Update a product
	// (PUT /products)
	Update(c *gin.Context)
	// Create many products
	// (POST /products/list)
	CreateMany(c *gin.Context)
	// Get products price with discounts
	// (GET /products/price/{uuids})
	GetPrice(c *gin.Context, uuids []openapi_types.UUID)
	// Get product by ID
	// (GET /products/{id})
	Get(c *gin.Context, id openapi_types.UUID)
	// Disable a product
	// (PUT /products/{id}/disable)
	Disable(c *gin.Context, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetList operation middleware
func (siw *ServerInterfaceWrapper) GetList(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetList(c)
}

// Create operation middleware
func (siw *ServerInterfaceWrapper) Create(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Create(c)
}

// Update operation middleware
func (siw *ServerInterfaceWrapper) Update(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Update(c)
}

// CreateMany operation middleware
func (siw *ServerInterfaceWrapper) CreateMany(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateMany(c)
}

// GetPrice operation middleware
func (siw *ServerInterfaceWrapper) GetPrice(c *gin.Context) {

	var err error

	// ------------- Path parameter "uuids" -------------
	var uuids []openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "uuids", c.Param("uuids"), &uuids)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter uuids: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPrice(c, uuids)
}

// Get operation middleware
func (siw *ServerInterfaceWrapper) Get(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Get(c, id)
}

// Disable operation middleware
func (siw *ServerInterfaceWrapper) Disable(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Disable(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/products", wrapper.GetList)
	router.POST(options.BaseURL+"/products", wrapper.Create)
	router.PUT(options.BaseURL+"/products", wrapper.Update)
	router.POST(options.BaseURL+"/products/list", wrapper.CreateMany)
	router.GET(options.BaseURL+"/products/price/:uuids", wrapper.GetPrice)
	router.GET(options.BaseURL+"/products/:id", wrapper.Get)
	router.PUT(options.BaseURL+"/products/:id/disable", wrapper.Disable)
}
