name: "[xor-java] Build Java monorepo"

on:
  push:
    branches: [ "master" ]
    paths: [ "xor-java/**" ]
  pull_request:
    branches: [ "master" ]
    paths: [ "xor-java/**" ]
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.9

jobs:
  build:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Prepare protos
        run: python3 ./xor-python/scripts/prepare_protos.py --xor-java

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.1.0

      - name: Execute Gradle build
        run: ./gradlew build
        working-directory: ./xor-java
