name: "[xor-go] Build Golang monorepo"

on:
  push:
    branches: ["master"]
    paths: ["xor-go/**"]
  pull_request:
    branches: ["master"]
    paths: ["xor-go/**"]
  workflow_dispatch:

jobs:
  sage-build:
    uses: ./.github/workflows/xor-go-build.yml
    with:
      service: sage

#  sage-docker:
#    needs: [sage-build]
#    uses: ./.github/workflows/build-push-docker-image.yml
#    with:
#      service: sage
#    secrets:
#      DOCKER_HUB_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
#      DOCKER_HUB_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}

  finances-build:
    uses: ./.github/workflows/xor-go-build.yml
    with:
      service: finances
