name: "[xor-java] Build with Gradle"

on:
  push:
    branches: ["master"]
    paths: ["xor-java/**"]
  pull_request:
    branches: ["master"]
    paths: ["xor-java/**"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./xor-java

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Execute Gradle build
      run: ./gradlew build
