name: "[xor-go] [sage] Build Golang"

on:
  push:
    branches: ["master"]
    paths: ["xor-go/**"]
  pull_request:
    branches: ["master"]
    paths: ["xor-go/**"]
  workflow_dispatch:

jobs:
  # The “build” workflow
  build-sage:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./xor-go

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
#        with:
#          go-version: 1.21
      - name: Run build
        run: go build -o sage ./service/sage/cmd/main.go
